from ..state import FPLState

def generate_report_node(state: FPLState) -> dict:
    """
    Final node that aggregates agent logs into a clean, markdown-formatted report.
    This doesn't necessarily need another LLM call if the previous agents already 
    output clean markdown, but here we just assemble it.
    """
    if state.get("error"):
        return {"final_report_markdown": f"# FPL Report Error\n\nThe FPL API could not be reached: {state['error']}"}

    gw = state.get("current_gameweek")
    captain_picks = state.get("captain_picks_report_markdown", "No captain picks generated.")
    transfer_picks = state.get("transfer_suggestions_report_markdown", "No transfer picks generated.")
    
    final_report = f"# FPL AI Copilot Gameweek {gw} Briefing\n\n"
    
    final_report += "## 🎯 Captain Recommendations\n"
    final_report += captain_picks + "\n\n"
    
    final_report += "## 🔄 Transfer Strategy\n"
    final_report += transfer_picks + "\n\n"
    
    final_report += "---\n*Generated by FPL AI Copilot using LLaMA-3*"
    
    return {"final_report_markdown": final_report}
